#!/bin/python3

string = "1" * 2018 + "3" * 2019

while "111" in string:
	string = string.replace("111", "2", 1)
	string = string.replace("222", "3", 1)
	string = string.replace("333", "1", 1)

print(string) # 321
