#!/bin/python3

string = ">" + "1" * 30 + "2" * 20 + "3" * 10
count = 0

while (">1" in string) or (">2" in string) or (">3" in string):
	string = string.replace(">1", "2>3", 1)
	string = string.replace(">2", "33>", 1)
	string = string.replace(">3", "1>22", 1)

string = list(string.replace(">", "", 1))
for i in string:
	count += int(i)

print(count) # 700
